# 开发环境配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/flexes_platform?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  
  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: none  # 让 Flyway 完全管理数据库结构
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true

  # Flyway 配置
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
  
  # Redis 配置
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:123456}
  
  # 开发工具配置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true

# 日志配置
logging:
  level:
    com.flexes: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

# Flexes 开发环境配置
flexes:
  # JWT 配置 (开发环境使用较短的过期时间便于测试)
  jwt:
    secret: flexes-dev-jwt-secret-key-2025-secure-256bit-minimum
    expiration: 3600000 # 1小时
    refresh-expiration: 86400000 # 24小时
  
  # 业务规则配置 (开发环境放宽限制)
  business:
    daily-application-limit: 50
    job-approval-required: false
    email-verification-required: false
  
  # 文件存储配置
  file:
    upload-path: uploads/dev/
    base-url: http://localhost:8081/api/files/
  
  # 邮件配置 (开发环境禁用)
  mail:
    enabled: false
  
  # 跨域配置 (开发环境允许所有来源)
  cors:
    allowed-origins: "*"

# 管理端点配置 (开发环境暴露更多端点)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
