# Flexes 远程工程招聘平台配置文件
# 主配置文件 - 通用配置

server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active: dev
  
  application:
    name: flexes-backend
  
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1800000
      pool-name: FlexesHikariCP
      connection-test-query: SELECT 1
  
  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.SnakeCasePhysicalNamingStrategy
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        generate_statistics: false
  
  # Redis 配置
  redis:
    timeout: 2000ms
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  
  # Jackson 配置
  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd HH:mm:ss
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true
  
  # 缓存配置
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1小时
      cache-null-values: false

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    redis:
      enabled: true
    db:
      enabled: true

# 日志配置
logging:
  level:
    root: INFO
    com.flexes: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/flexes-backend.log
    max-size: 100MB
    max-history: 30

# Flexes 应用配置
flexes:
  # JWT 配置
  jwt:
    secret: flexes-jwt-secret-key-2025-change-in-production
    expiration: 86400000 # 24小时
    refresh-expiration: 604800000 # 7天
  
  # 业务规则配置
  business:
    daily-application-limit: 20
    job-approval-required: true
    email-verification-required: true
    max-resume-size: 5242880 # 5MB
    allowed-resume-types: pdf,doc,docx
  
  # 文件存储配置
  file:
    upload-path: uploads/
    base-url: http://localhost:8080/api/files/
  
  # 邮件配置
  mail:
    enabled: false
    from: noreply@flexes.work
    support: support@flexes.work
  
  # 跨域配置
  cors:
    allowed-origins: 
      - http://localhost:3000
      - http://127.0.0.1:3000
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

# SpringDoc OpenAPI 配置
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
  info:
    title: Flexes API
    description: Flexes 远程工程招聘平台 REST API 文档
    version: 1.0.0
    contact:
      name: Flexes Team
      email: dev@flexes.work
    license:
      name: MIT License
      url: https://opensource.org/licenses/MIT
